import "./globals.css";

export const metadata = {
  title: "Art Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <div>
            {children}
        </div>
      </body>
    </html>
  );
}
