import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Art Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
